// ─────────────────────────────────────────────
// named.conf — bind9 avec DNSSEC
// Zone : home.arpa → jeu-2002.home.arpa
// ─────────────────────────────────────────────

options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query     { any; };
    allow-recursion { any; };
    listen-on       { any; };
    listen-on-v6    { none; };

    // DNSSEC activé
    dnssec-validation auto;

    // Forwarders — pour les autres domaines
    forwarders { 8.8.8.8; 8.8.4.4; };
    forward only;
};

// Zone home.arpa — contient jeu-2002.home.arpa
zone "home.arpa" {
    type master;
    file "/etc/bind/zones/home.arpa.zone";
    allow-query { any; };
    key-directory "/etc/bind/keys";
};
