server {
    listen 80;
    server_name jeu-2002.home.arpa www.jeu-2002.home.arpa;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name jeu-2002.home.arpa www.jeu-2002.home.arpa localhost;

    ssl_certificate     /shared/pki/server_fullchain.crt;
    ssl_certificate_key /shared/pki/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers   HIGH:!aNULL:!MD5;

    resolver 127.0.0.11 valid=30s;

    location / {
        proxy_pass         http://127.0.0.1:8888;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 8888;
    server_name localhost;
    root  /var/www/html;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
